--CREATE DATABASE AB106
--USE AB106

--CREATE TABLE STUDENTS(
--ID INT PRIMARY KEY IDENTITY(1,1),
--[NAME] NVARCHAR(16) NOT NULL,
--SURNAME NVARCHAR(16) DEFAULT 'XXX',
--AGE INT CHECK(AGE>18),
--AVGPOINT FLOAT CHECK(AVGPOINT BETWEEN 0 AND 100)
--)

--INSERT INTO STUDENTS([NAME],SURNAME,AGE,AVGPOINT)
--VALUES(N'Nurlan',N'ABBASOV',20,95),
--(N'ASCVJ',N'ASCBƏSA',25,50)

SELECT * FROM STUDENTS WHERE AVGPOINT>=51 
SELECT * FROM STUDENTS WHERE AVGPOINT>=51 AND AVGPOINT<=90
SELECT * FROM STUDENTS WHERE NAME LIKE 'A%' AND NAME LIKE'%I'